package org.DuAn.WebBanHangThoiTrang.Entity;
// Generated Sep 5, 2019, 8:31:35 PM by Hibernate Tools 5.2.12.Final

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private String userName;
	private String password;
	private boolean active;
	private String userRole;

	public Accounts() {
	}

	public Accounts(String userName, String password, boolean active, String userRole) {
		this.userName = userName;
		this.password = password;
		this.active = active;
		this.userRole = userRole;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

}
