package org.DuAn.WebBanHangThoiTrang.Entity;
// Generated Sep 5, 2019, 8:31:35 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String id;
	private double amount;
	private String customerAdress;
	private String customerEmail;
	private String customerName;
	private String customerPhone;
	private Date orderDate;
	private int orderNum;
	private Set orderDetailses = new HashSet(0);

	public Orders() {
	}

	public Orders(String id, double amount, String customerAdress, String customerEmail, String customerName,
			String customerPhone, Date orderDate, int orderNum) {
		this.id = id;
		this.amount = amount;
		this.customerAdress = customerAdress;
		this.customerEmail = customerEmail;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.orderDate = orderDate;
		this.orderNum = orderNum;
	}

	public Orders(String id, double amount, String customerAdress, String customerEmail, String customerName,
			String customerPhone, Date orderDate, int orderNum, Set orderDetailses) {
		this.id = id;
		this.amount = amount;
		this.customerAdress = customerAdress;
		this.customerEmail = customerEmail;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.orderDate = orderDate;
		this.orderNum = orderNum;
		this.orderDetailses = orderDetailses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getCustomerAdress() {
		return this.customerAdress;
	}

	public void setCustomerAdress(String customerAdress) {
		this.customerAdress = customerAdress;
	}

	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
