package org.DuAn.WebBanHangThoiTrang.Entity;
// Generated Sep 5, 2019, 8:31:35 PM by Hibernate Tools 5.2.12.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private String id;
	private Orders orders;
	private Products products;
	private double amount;
	private double price;
	private int quanity;

	public OrderDetails() {
	}

	public OrderDetails(String id, Orders orders, Products products, double amount, double price, int quanity) {
		this.id = id;
		this.orders = orders;
		this.products = products;
		this.amount = amount;
		this.price = price;
		this.quanity = quanity;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuanity() {
		return this.quanity;
	}

	public void setQuanity(int quanity) {
		this.quanity = quanity;
	}

}
