package org.DuAn.WebBanHangThoiTrang.Entity;
// Generated Sep 5, 2019, 8:31:35 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private String code;
	private Date createDate;
	private byte[] image;
	private String name;
	private double price;
	private Set orderDetailses = new HashSet(0);

	public Products() {
	}

	public Products(String code, Date createDate, byte[] image, String name, double price) {
		this.code = code;
		this.createDate = createDate;
		this.image = image;
		this.name = name;
		this.price = price;
	}

	public Products(String code, Date createDate, byte[] image, String name, double price, Set orderDetailses) {
		this.code = code;
		this.createDate = createDate;
		this.image = image;
		this.name = name;
		this.price = price;
		this.orderDetailses = orderDetailses;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
